2021-04-09 18:19:26,422 - gravity_core.wlogger - ERROR - Выход не зафиксирован фотоэлементом
2021-04-10 07:53:59,651 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/watchman/Gravity-Core/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-04-10 07:53:59,657 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/watchman/Gravity-Core/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
ConnectionResetError: [Errno 104] Connection reset by peer

2021-04-10 07:54:02,063 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/watchman/Gravity-Core/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-04-10 07:54:02,065 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/watchman/Gravity-Core/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-04-10 07:54:04,678 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/watchman/Gravity-Core/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

2021-04-10 07:54:04,681 - gravity_core.wlogger - ERROR - Traceback (most recent call last):
  File "/home/watchman/Gravity-Core/gravity_core/wlistener.py", line 102, in broadcastMsgSend
    conn.send(msg)
BrokenPipeError: [Errno 32] Broken pipe

